language: d
d:
- dmd
- ldc
sudo: false
addons:
  apt:
    packages:
    - libevent-dev
before_install:
- pip install --user codecov
- dub fetch packageversion
script:
- dub test --compiler=${DC} --coverage
- dub build --compiler=${DC} --build=release
- dub build --compiler=${DC} --build=ddox
after_success: codecov
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: "$GH_REPO_TOKEN"
  verbose: true
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: reYM++hAVh1SO6nMdwGsgFf72KjkarSaGl2rgFDQez/lnVmb81qHONaJDhYezVOINx/76S/clK+XUH99gCKDfPM9n+8ElhRdxpxBZaz15AI5HDJkOqFw20VHZ9QVCVND1T/S95AO3irXmXbdh/MOBVbdK9ZSyFloLNqa2wqt1Zya6tlCtBWKh+MI8/Y17NdkGNNNtyONk1syXXxLBR6p28m7u9zaJAQ/7p8owZEOyzD7D4i4nllxZ5d0TNZA2EnBooKJ4XA/xQ4b4I012eJ3N053Uwn5ZAi9FM9/63V+xz/dCTOuFsdp69sYyuHWcaBN8GmMf2ZxjL/XWFh1264dVUg6r557S37Wx49D/T+sdFvuWhKv+++a2m8wVuPqqsiEt3d2w+qmnejmXOuUUfSOI4OfFn93XnKLgf38WKTTJZBKDck094fXA8wwVrjbOpGe16sartEBFAb40yRo75tOXgSGTv+rPjP2Rq3oIknJS2v3ZJ2hpKUdbYifs1Mkym9GzlcDH3tSjq5Giex9IMNLQ4S+Uw5cFMLXmtfHSv8nbFbs1crfi8jvd8TQumUd1e2UW4dKXHC27Uk3wmpDkEgVSZ7UBjJwvQxSsIYdhXKP7QfobPD65JPsi712uyY9ti7oH0VvDEX/tQ1QTI5oXhhM8XJPu0ASAjGs4Z91lnwFj/A=
